spring.application.name=warehouse-management
spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/warehouse_management}
spring.datasource.username=${DB_USER:warehouse_app}
spring.datasource.password=${DB_PASSWORD:warehouse123}
spring.sql.init.mode=never
